GET http://localhost:8080/newGame

###

PUT http://localhost:8080/makeMove
Content-Type: application/json

{
  "gameId": 123,
  "position": 1
}

###

PUT http://localhost:8080/makeMove
Content-Type: application/json

{
  "gameId": 123,
  "position": 2
}

###

PUT http://localhost:8080/makeMove
Content-Type: application/json

{
  "gameId": 123,
  "position": 5
}

###

PUT http://localhost:8080/makeMove
Content-Type: application/json

{
  "gameId": 123,
  "position": 3
}

###

PUT http://localhost:8080/makeMove
Content-Type: application/json

{
  "gameId": 123,
  "position": 9
}

###

PUT http://localhost:8080/makeMove
Content-Type: application/json

{
  "gameId": 123,
  "position": 1
}

###

PUT http://localhost:8080/makeMove
Content-Type: application/json

{
  "gameId": 123,
  "position": 1
}

